---
name: TGCapes
author: Theslowaja
version: 2.1.0
description: Wear Capes on your Pocketmine-MP Server!
main: Theslowaja\TGCapes\Main
api: 5.0.0
extensions: [gd]

commands:
  cape:
    description: Choose a Cape!
    usage: /cape
    permission: tgcape.cmd

permissions:
  tgcape.cmd:
    default: true
    description: "Allows to open the Cape UI"
    
...
