---
name: TGCapes
author: Theslowaja
version: 2.0.0
description: Wear Capes on your Pocketmine-MP Server!
main: Theslowaja\TGCapes\Main
api: 4.0.0
extensions: [gd]

commands:
  cape:
    description: Choose a Cape!
    usage: /cape
    permission: cape.cmd

permissions:
  cape.cmd:
    default: true
    description: "Allows to open the Cape UI"
    
...
